version: "3.9"

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: pgvector_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PGDATABASE:-interviewqa}
      POSTGRES_USER: ${PGUSER:-postgres}
      POSTGRES_PASSWORD: ${PGPASSWORD:-postgres}
    ports:
      - "${PGPORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER:-postgres} -d ${PGDATABASE:-interviewqa}"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  pgdata:
